var colorName = [];
var firstColor = prompt("What color you want at the start of the array?");
colorName[0] = firstColor;
document.write(colorName + "<br>");
var secondColor = prompt("What color you want to add to the end?");
colorName.push(secondColor);
document.write(colorName + "<br>");
colorName.unshift("Yellow", "Cyan");
document.write(colorName + "<br>");
colorName.shift();
document.write(colorName + "<br>");
colorName.pop();
document.write(colorName + "<br>");
var askColor = prompt("Input Desired Color");
var colorIndex = parseInt(prompt("At which index you want to add this color?"),10);
colorName.splice(colorIndex, 0, askColor);
document.write(colorName + "<br>");
var delColorIndex = prompt("At which index you want to delete the color?");
var noOfdeleteColors = prompt("How many colors you want to delete?");
colorName.splice(delColorIndex, noOfdeleteColors);
document.write(colorName);